/* 定义每个 db_header 在文件中的位置.

一个数据文件由以下部分组成:

* 数据块.
* 索引数据块(类型为 DataBlockIndices).
* 索引数据块指针(8 字节).
* 文件结束标识符(4 字节). 0x5af00f5a

文件最后的 4 个字节固定为大端存储的 0x5af00f5a 作为文件结束标识符. 如果一个文件不存在这四个字节可以认为文件已损坏(损坏文件可以修复).
文件最后倒数的第 5 到第 12 个字节(共 8 字节)组成一个大端存储的 uint64 保存了索引数据块起始位置.
知道索引数据块起始位置和索引数据块大小(索引起始-12)之后, 就可以解析索引数据块并获得文件所有数据块的索引了.

一个数据块由以下部分组成:

* 4 字节数据块起始标识符. 大端存放的 0x5af00f5a.
* 不定长度的 c 字符串标识数据块类型(c 字符串指的是字符串以 `\0` 结尾). 如点云为 `P`(包含 \0 共 2 字节), 目标列表为 `O`, 间隔帧为 `Frsp`.
* 4 字节数据块长度. 大端存放.
* n 字节数据. 对于间隔帧为 0 字节.

为什么数据块不直接包含数据, 而是加上了标识符, 类型, 数据长度这些头部信息?

因为这些信息可以帮助我们进行数据修复. 对于一个完整的文件. 我们可以直接读取索引数据块. 快速确定每个数据块所在的位置, 类型, 数据块大小.
但是在实际采集数据时, 可能发生数据采集的一半意外停止采集的情况, 此时数据索引帧往往未被写入. 因此不能通过索引帧快速分析文件的数据块.
由于写入文件时, 每一个数据块都有对应的头部信息, 我们就可以通过遍历整个文件的方式, 重新生成索引帧. 而不是直接丢弃整个文件.

当将所有的数据序列化到一个文件后, 为了方便对各个数据块进行索引,
将所有的数据块头的位置记录到本数据块中.

* 一般情况下, 本数据块为序列化文件的最后一个 protobuf 数据块.
* 本数据块后, 还需要放置一个大端存储的 8 字节的 uint64
用来定位本数据块的起始位置. 文件最后还需放置 4 字节的文件结束标识符 0x5af00f5a.
* 序列化文件的解析顺序为: 先读取最后 4 字节判断文件是否损坏, 然后读取倒数的第 5 到第 12 个字节确定本数据块头位置,
最后读取本数据块确定所有数据块位置.
*/

syntax = "proto3";
package ld_data;

enum DataBlockType {
  UNKNOWN = 0;
  FRAME_SPLITER = 1;
  POINT_CLOUD = 2;
  OBJECT_LIST = 3;
}

message DataBlockIdx {
  DataBlockType type = 1;
  // uint32 type = 1;
  uint64 timestamp = 2;
  uint64 pos = 3; // 直接是 protobuf 数据块的起始位置, 不包含头部的起始标识符, 数据块标识符等. 直接从该位置读取数据然后解析.
  uint32 block_size = 4; // 每个数据块大小不能超过 4G 字节(2^32).
  string name = 5;
}

message DataBlockIndices { repeated DataBlockIdx indices = 1; }