// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "point_cloud.proto" (package "ld_data", syntax proto3)
// tslint:disable
//
//! 用来定义点云的类型, 后续所有的点云数据块都会按照
//本数据块定义的格式进行解析, 直到遇到新的点云定义数据块.
//
//本数据块的作用类似于 pcd 文件中的 header.
//
// name: 用来标识点云. 比如 rosbag 文件中 pointcloud2 的 msg topic.
// id: 设备编号.
// timestamp: 时间戳.
// fields: ',' 分割的字符串, 用来定义字段名. 如 "x,y,z" 表示有 x,y,z 三个字段.
// types: ',' 分割的字符串, 用来定义各个字段的数据类型. 每个数据类型由 i,u,f(不区分大小写) 和一个代表位数的数字组成.
// i 表示有符号整数.
// u 表示无符号整数.
// f 表示浮点数.
//如 "f32,f32,f32" 表示三个字段都是 4 字节浮点数.
// shape: ',' 分割的字符串, 用来表示数据的维度(可选). 类似于 pcd 文件中的 width, heigh. 相较于 pcd 文件这里的定义更加泛化. 可以超过 2 个维度.如 "1000,500,5". 点云总数为所有维度的乘积. 如果点云是无序的, 则该字段为一个整数, 直接表示总点数.
// is_bigendian: 是否为大端存储.
// data: 点云数据. 根据 protobuf 定义, bytes 不能超过 2^32 个字节, 即 4G.
//一般点云数据也不会超过 4G.
//
//数据示例:
//{
//name = "my_lidar";
//id = 1;
//timestamp = 2234558;
//fields = "x,y,z,intensity,rgb";
//types = "f32,f32,f32,u8,u32";
//shape = "400,600,10";
//is_bigendian = 0;
//data = [2400000*(4+4+4+1+4) 个字节的数组];
//}
//
//标识符: "P"
//
//参考资料 [pcd file format](http://pointclouds.org/documentation/tutorials/pcd_file_format.html).
//[sensor_msgs/PointCloud2.msg](http://docs.ros.org/en/api/sensor_msgs/html/msg/PointCloud2.html).
//
import type { BinaryWriteOptions } from '@protobuf-ts/runtime'
import type { IBinaryWriter } from '@protobuf-ts/runtime'
import { WireType } from '@protobuf-ts/runtime'
import type { BinaryReadOptions } from '@protobuf-ts/runtime'
import type { IBinaryReader } from '@protobuf-ts/runtime'
import { UnknownFieldHandler } from '@protobuf-ts/runtime'
import type { PartialMessage } from '@protobuf-ts/runtime'
import { reflectionMergePartial } from '@protobuf-ts/runtime'
import { MESSAGE_TYPE } from '@protobuf-ts/runtime'
import { MessageType } from '@protobuf-ts/runtime'
/**
 * @generated from protobuf message ld_data.PointCloud
 */
export interface PointCloud {
  /**
   * @generated from protobuf field: string name = 1;
   */
  name: string
  /**
   * @generated from protobuf field: uint64 id = 2;
   */
  id: bigint
  /**
   * @generated from protobuf field: uint64 timestamp = 3;
   */
  timestamp: bigint
  /**
   * @generated from protobuf field: string fields = 4;
   */
  fields: string
  /**
   * @generated from protobuf field: string types = 5;
   */
  types: string
  /**
   * @generated from protobuf field: string shape = 6;
   */
  shape: string
  /**
   * @generated from protobuf field: bool is_bigendian = 7;
   */
  isBigendian: boolean
  /**
   * @generated from protobuf field: bytes data = 8;
   */
  data: Uint8Array
}
// @generated message type with reflection information, may provide speed optimized methods
class PointCloud$Type extends MessageType<PointCloud> {
  constructor() {
    super('ld_data.PointCloud', [
      { no: 1, name: 'name', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
      { no: 2, name: 'id', kind: 'scalar', T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
      {
        no: 3,
        name: 'timestamp',
        kind: 'scalar',
        T: 4 /*ScalarType.UINT64*/,
        L: 0 /*LongType.BIGINT*/,
      },
      { no: 4, name: 'fields', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
      { no: 5, name: 'types', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
      { no: 6, name: 'shape', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
      { no: 7, name: 'is_bigendian', kind: 'scalar', T: 8 /*ScalarType.BOOL*/ },
      { no: 8, name: 'data', kind: 'scalar', T: 12 /*ScalarType.BYTES*/ },
    ])
  }
  create(value?: PartialMessage<PointCloud>): PointCloud {
    const message = {
      name: '',
      id: 0n,
      timestamp: 0n,
      fields: '',
      types: '',
      shape: '',
      isBigendian: false,
      data: new Uint8Array(0),
    }
    globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this })
    if (value !== undefined) reflectionMergePartial<PointCloud>(this, message, value)
    return message
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: PointCloud
  ): PointCloud {
    let message = target ?? this.create(),
      end = reader.pos + length
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag()
      switch (fieldNo) {
        case /* string name */ 1:
          message.name = reader.string()
          break
        case /* uint64 id */ 2:
          message.id = reader.uint64().toBigInt()
          break
        case /* uint64 timestamp */ 3:
          message.timestamp = reader.uint64().toBigInt()
          break
        case /* string fields */ 4:
          message.fields = reader.string()
          break
        case /* string types */ 5:
          message.types = reader.string()
          break
        case /* string shape */ 6:
          message.shape = reader.string()
          break
        case /* bool is_bigendian */ 7:
          message.isBigendian = reader.bool()
          break
        case /* bytes data */ 8:
          message.data = reader.bytes()
          break
        default:
          let u = options.readUnknownField
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
            )
          let d = reader.skip(wireType)
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d
            )
      }
    }
    return message
  }
  internalBinaryWrite(
    message: PointCloud,
    writer: IBinaryWriter,
    options: BinaryWriteOptions
  ): IBinaryWriter {
    /* string name = 1; */
    if (message.name !== '') writer.tag(1, WireType.LengthDelimited).string(message.name)
    /* uint64 id = 2; */
    if (message.id !== 0n) writer.tag(2, WireType.Varint).uint64(message.id)
    /* uint64 timestamp = 3; */
    if (message.timestamp !== 0n) writer.tag(3, WireType.Varint).uint64(message.timestamp)
    /* string fields = 4; */
    if (message.fields !== '') writer.tag(4, WireType.LengthDelimited).string(message.fields)
    /* string types = 5; */
    if (message.types !== '') writer.tag(5, WireType.LengthDelimited).string(message.types)
    /* string shape = 6; */
    if (message.shape !== '') writer.tag(6, WireType.LengthDelimited).string(message.shape)
    /* bool is_bigendian = 7; */
    if (message.isBigendian !== false) writer.tag(7, WireType.Varint).bool(message.isBigendian)
    /* bytes data = 8; */
    if (message.data.length) writer.tag(8, WireType.LengthDelimited).bytes(message.data)
    let u = options.writeUnknownFields
    if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer)
    return writer
  }
}
/**
 * @generated MessageType for protobuf message ld_data.PointCloud
 */
export const PointCloud = new PointCloud$Type()
